# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_auto_20160304_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='price',
        ),
    ]
