# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-06 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_auto_20160305_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
