# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_auto_20160308_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='accounts',
        ),
        migrations.AlterField(
            model_name='account',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='accounting.Book'),
        ),
    ]
