# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 17:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_auto_20160310_1709'),
    ]

    operations = [
        migrations.RunSQL("""
CREATE VIEW IF NOT EXISTS accounting_priceditem AS SELECT item.id, purchase_id, item.product_id, price.amount * item.amount AS price
FROM accounting_purchaseitem item
JOIN accounting_product product ON item.product_id = product.id
JOIN accounting_purchase purchase ON item.purchase_id = purchase.id
JOIN accounting_price price ON price.product_id = product.id
WHERE price.date <= purchase.date AND price.date = (SELECT max(date)
                                                    FROM accounting_price price
                                                    WHERE price.date <= purchase.date
                                                          AND price.product_id = product.id);
        """)
    ]
